type: "position_controllers/JointGroupPositionController"
joints: 
  - base_to_finger_1_1
  - finger_1_1_to_finger_1_2
  - finger_1_2_to_finger_1_3
  - base_to_finger_2_1
  - finger_2_1_to_finger_2_2
  - finger_2_2_to_finger_2_3
  - base_to_finger_3_1
  - finger_3_1_to_finger_3_2
  - finger_3_2_to_finger_3_3